06 lection4/02 background image
js-tasks-ru/htmlcss-20220120_a-k-r-a pull request #28
Opened 2022-02-05 16:12 UTC by anna-kra

Added solution for 06-lection4/02-background-image

2022-02-05 16:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-06 21:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-06 21:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-08 11:57 UTC, GSemikozov requested changes

2022-02-08 11:57 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 399.98px) {
дробные пиксели не используем, можно просто 400

2022-02-08 11:57 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 399.98px) {
или 399

2022-02-08 11:57 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 399.98px) {
а еще лучше задать эту картинку по умолчанию (будет отображаться пока не переопределится в min-width: 400px)

2022-02-08 12:54 UTC, anna-kra commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 399.98px) {
Поправила. 

Дробные пиксели употребляет временами bootstrap. Я их не понимаю, но решила попробовать. 
https://getbootstrap.com/docs/5.1/layout/breakpoints/  @media (max-width: 575.98px) { ... }

2022-02-08 13:12 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 399.98px) {
в большей степени это актуально когда используем параллельно min + max - либо с одной точкой разрыва (400px; max заканчивается на этой точке, min - начинается, из-за чего конкретно на одном пиксели будет наложение), либо желая указать range; и пока браузеры не поддерживают range context queries, в таком случае бутстрап предлагает использовать дробные пиксели. Но - для нас эти сложности сейчас не столь важны

2022-02-08 13:13 UTC, GSemikozov approved these changes

2022-02-08 13:13 UTC, merged