add a solution for component page
js-tasks-ru/htmlcss-20220120_a-k-r-a pull request #30
Opened 2022-02-08 08:06 UTC by anna-kra

Решение для страницы компонента. 
Для маленьких экранов навигация убирается, но пока нет ещё решения, как включать её обратно.

2022-02-08 08:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-08 09:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-08 11:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-08 12:17 UTC, GSemikozov requested changes

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__header {
это внутренние свойства компонента, ими правильнее будет управлять на уровне модификатора самого компонента

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__container {
точно ли есть необходимость принудительно растягивать на всю высоту этот контейнер? скорее, достаточно будет растянуть main

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__main {
элементы main + nav + component лучше сразу вынести в качестве отдельных компонентов

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +  z-index: 200;
а для чего здесь z-index? кроме того, здесь элемент не выделяется на отдельный контекст наложения, z-index все равно работать не будет

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +  margin-right: 56px;
если это будет отдельный компонент, тогда на уровне блока марджины задавать нельзя, их надо будет задать на уровне родителя (того блока куда будем встраивать данный)

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +  height: 100%;
в этом нет необходимости

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__footer {
у нас уже есть футер, его внутренние свойства лучше менять через ему же принадлежащий модификатор

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +  font-weight: 500;
а текст - оформить отдельным элементом

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__header-controls {
controls, burger, logo, nav - это все элементы блока header, это не элементы .component-page. Поэтому - нужно унести в header

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__nav-links li {
селекторы тэгов в БЭМ не используем, лучше задать класс

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__nav-link.active {
если модификатор, тогда просто .component-page__nav-link_active

2022-02-08 12:17 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__header-controls {
+ theme-toggler

2022-02-08 12:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-08 13:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-08 15:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-08 18:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-09 07:13 UTC, anna-kra commented on components/component-page/component-page.css
> +  z-index: 200;
Делала решение для меню в мобильных вариантах. Там потребовался бы z-index. Решение пока не готово, удалила его, а этот кусочек кода не заметила.

2022-02-09 12:43 UTC, anna-kra commented on components/component-page/component-page.css
> +.component-page__container {
К сожалению, не получится. 
Сейчас каждая горизонтальная секция обёрнута в контейнер, который её центрирует и может задавать цвет для своей внутренней части, отличающийся от цвета по его сторонам. Эти контейнеры, если ничего не сказано, занимают ту высоту, которая необходима их внутренним элементам. Если же этим контейнерам указать 100% высоты, то они займут всё имеющееся в распоряжении пространство и внутренние части тоже вырастут (это предусмотрено). Другое дело, нужны ли нам на этой странице эти отдельные контейнеры для секций, если нам не нужен "полосатый" лэйоут? Может, ограничиться всего одним wrapper? Тогда надо переконструировать страничку.

2022-02-09 12:44 UTC, anna-kra commented on components/component-page/component-page.css
> +.component-page__header {
done:
.header__component-page

Переструктурировала всё, соответственно переименовала классы. 
Вместо component-page теперь template

Соответственно вместо 
.header__component-page
->
.header_template (то есть у header появляется модификатор, соответствующий названию всей страницы)

2022-02-09 12:44 UTC, anna-kra commented on components/component-page/component-page.css
> +.component-page__main {
done

2022-02-09 12:51 UTC, anna-kra commented on components/component-page/component-page.css
> +  margin-right: 56px;
Сделала отдельный компонент. Убрала из .nav и margins, и flex-basis. Добавила в родителя (который содержит два элемента) через :first-child

2022-02-09 12:55 UTC, anna-kra commented on components/component-page/component-page.css
> +.component-page__nav-links li {
done:
<li class="nav__links-item">

2022-02-09 12:56 UTC, anna-kra commented on components/component-page/component-page.css
> +.component-page__nav-link.active {
done

2022-02-09 13:11 UTC, anna-kra commented on components/component-page/component-page.css
> +  margin-right: 56px;
Сделала отдельный компонент .nav
Убрала из .nav и margin, и flex-basis. 
Добавила в родителя (который содержит два элемента): 
.template__middle .nav:first-child

Не уверена, что сделала правильно.

2022-02-09 13:13 UTC, anna-kra commented on components/component-page/component-page.css
> +  font-weight: 500;
done:
  <footer class="footer footer_template">
    <div class="container">
      <div class="footer__text_template">Reusable component library</div>
    </div>
  </footer>

2022-02-09 13:13 UTC, anna-kra commented on components/component-page/component-page.css
> +.component-page__header-controls {
done

2022-02-09 13:19 UTC, anna-kra commented on components/component-page/component-page.css
> +  height: 100%;
Тогда на маленьких экранах высота не держится. Посмотрела, как у вас в курсовом проекте, если мало содержимого в части для компонента - та же проблема, высота не держится.

2022-02-12 14:44 UTC, closed without merging