07 lection5/04 input
js-tasks-ru/htmlcss-20220120_a-k-r-a pull request #35
Opened 2022-02-13 20:47 UTC by anna-kra

Added solution for 07-lection5/04-input

2022-02-13 20:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-13 22:03 UTC, GSemikozov requested changes

2022-02-13 22:03 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <label for="f1" class="label">Label</label>
такую конструкцию в реальных формах мы скорее всего вряд ли будем использовать, все-таки правильнее - в том числе и сточки зрения БЭМ - завернуть лейбл и инпут в общий класс, класс по имени блока. Что касается самого инпута - я бы тоже советовал завернуть его в отдельный враппер - на случай если иконки будем добавлять как отдельные хтмл элементы + если захотим добавить helper-text с информацией об ошибке ниже инпута, иными словами - обеспечим возможное беспроблемное расширение функционала интупа

2022-02-13 22:03 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.label {
если блок .input - тогда .input__label

2022-02-13 22:03 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_text {
если элемент блока - .input__input-text

2022-02-13 22:03 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_text-success::placeholder,
модификаторы советовал бы вешать на общий враппер / на сам блок, чтобы был один общий модификатор для всех внутренних элементов

2022-02-14 07:28 UTC, anna-kra commented on 07-lection5/04-input/input.css
> +.input_text-success::placeholder,
Поменяла, как указано. Но ведь теперь не обойтись без вложенных селекторов? ->

.input-success .input__inputtext::placeholder

2022-02-14 07:29 UTC, anna-kra commented on 07-lection5/04-input/input.css
> +.input_text {
Поменяла (почти), как указано. 
.input__inputtext

2022-02-14 07:30 UTC, anna-kra commented on 07-lection5/04-input/input.css
> +.label {
Поменяла, как указано.

2022-02-14 08:28 UTC, anna-kra commented on 07-lection5/04-input/index.html
> +        <label for="f1" class="label">Label</label>
Поменяла. Добавила элемент .hint на случай, если будут появляться дополнительные информации.

2022-02-14 08:43 UTC, anna-kra commented
Changed solution for input.

2022-02-14 09:40 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_text-success::placeholder,
нет, вот как раз в таком случае использовать вложенные селекторы будет вполне ок) 
кроме того, если использовать пре-процессоры, то мы в любом случае будем использовать вложенность.

2022-02-14 09:44 UTC, GSemikozov requested changes

2022-02-14 09:44 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.container {
используем на одном уровне с блоком .input - по сути, это и есть стили блока, поэтому их надо унести в .input

2022-02-14 09:44 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input-container {
а этот блок нужно удалить из этого файла - не по БЭМ + если нужны отступы между блоками инпутов - они будут добавляться при сборке формы через миксы, в данном случае можно переместить в тег style хтмл страницы

2022-02-14 09:44 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__inputtext-success::placeholder,
сейчас оформлено как элементы, но - на самом деле это модификаторы. Повторюсь - лучше использовать 1 общий модификатор на уровне блока)

2022-02-14 10:14 UTC, anna-kra commented on 07-lection5/04-input/input.css
> +.container {
К сожалению, не могу согласиться. 
container – это временная конструкция. Будущее окружение, о котором мы ничего не знаем. 
Внутренние инпуты будут под такие контейнеры автоматически подстраиваться.

2022-02-14 10:19 UTC, anna-kra commented on 07-lection5/04-input/input.css
> +.input-container {
Так я и думала. Опять гит. Локально эта ошибка уже была исправлена. :-( :-( :-(

2022-02-14 10:24 UTC, anna-kra commented on 07-lection5/04-input/input.css
> +.input-container {
done

2022-02-14 10:29 UTC, anna-kra commented on 07-lection5/04-input/input.css
> +.input_text-success::placeholder,
done

2022-02-14 10:29 UTC, anna-kra commented on 07-lection5/04-input/input.css
> +.input__inputtext-success::placeholder,
done

2022-02-14 10:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-14 11:15 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.container {
верно, но вспомогательному / иллюстративному блоку .container в стилях блока .input не место)

2022-02-14 11:17 UTC, GSemikozov approved these changes

2022-02-14 11:18 UTC, merged