03 lection1/01 button
js-tasks-ru/htmlcss-20220120_a-k-r-a pull request #6
Opened 2022-01-21 03:51 UTC by anna-kra

Попытка решить проблемы, связанные с неверным использованием веток. Задание из первой лекции, упражнение с кнопками.

2022-01-21 03:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-22 04:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-25 22:02 UTC, GSemikozov requested changes

2022-01-25 22:02 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  display: flex;
кнопку блочной делать не стоит, гораздо чаще удобнее будет использовать inline-flex

2022-01-25 22:02 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-weight: 500;
не хватает стилей для описание текста + паддингов

2022-01-26 00:03 UTC, anna-kra commented
Спасибо. Добавила. Думала, что стили для шрифтов каскадируются из body. Но button их почему-то не перенял, так что продублировала код. Очень странно.

2022-01-27 21:42 UTC, GSemikozov requested changes

2022-01-27 21:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-family: 'Inter', sans-serif;
а у кнопок здесь Roboto

2022-01-27 21:42 UTC, GSemikozov commented on index.html
> +            <header class="page__inner page__header">
inner пусть будет внутри хедера (кейс почему - разобрали на занятии)

2022-01-28 00:45 UTC, anna-kra reviewed
Перенесла состояние файла index.html в другую ветку. Здесь содержимое удалила. 
Буду коммитить из собственной, новой ветки.

2022-01-28 19:05 UTC, GSemikozov approved these changes

2022-01-28 19:05 UTC, merged