03 lection1/02 accordeon
js-tasks-ru/htmlcss-20220120_a-k-r-a pull request #7
Opened 2022-01-22 11:24 UTC by anna-kra

Add a solution for 03 lection1/02 accordeon.

2022-01-22 11:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-25 23:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-27 21:46 UTC, GSemikozov requested changes

2022-01-27 21:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  max-width: 730px;
это будет лишним ограниченим

2022-01-27 21:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: .5em;
на уровне блока марджины не задаем

2022-01-27 21:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion:last-child {
если хочется margin-bottom - аккордион-секции предлагаю отдельно оформить как .accordion__item

2022-01-27 21:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding-right: .5em;
для чего именно такой паддинг справа? резерв для иконки?

2022-01-27 21:46 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion">
пусть это будет .accordion__item. И тогда все эти айтемы можно завернуть в общий div с классом .accordion

2022-01-27 22:15 UTC, anna-kra commented on 03-lection1/02-accordion/accordion.css
> +  padding-right: .5em;
Yes…

2022-01-27 22:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-27 22:58 UTC, anna-kra commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion">
Спасибо большое, внесла изменения согласно правкам.

2022-01-28 00:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-28 02:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-28 02:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-28 19:08 UTC, GSemikozov approved these changes

2022-01-28 19:08 UTC, merged